Make command work when in the non-root directory of a repo, or from the top-level of a bare repo.
Signed-off-by: Brett Randall <javabrett@gmail.com>

diff --git a/git-discover-large-blobs b/git-discover-large-blobs
--- a/git-discover-large-blobs
+++ b/git-discover-large-blobs
@@ -5,12 +5,33 @@
 #
 # @see http://stubbisms.wordpress.com/2009/07/10/git-script-to-show-largest-pack-objects-and-trim-your-waist-line/
 # @author Antony Stubbs
+# ChangeLog
+#
+#       Originally by Antony Stubbs http://stubbisms.wordpress.com/2009/07/10/git-script-to-show-largest-pack-objects-and-trim-your-waist-line/
+#
+#       <javabrett>
+#       - Make command work when in the non-root directory of a repo, or from the top-level of a bare repo
+#
+
 
 # set the internal field separator to line break, so that we can iterate easily over the verify-pack output
 IFS=$'\n';
 
+# find top-level dir of a non-bare repo
+_GIT_DIR=`git rev-parse --show-toplevel` || exit 1
+
+if [ -n ${_GIT_DIR} ] && [ -d ${_GIT_DIR}/.git/objects/pack ]; then
+	PACK_DIR=${_GIT_DIR}/.git/objects/pack
+elif [ -d ./objects/pack ]; then
+	# bare repo
+	PACK_DIR=./objects/pack
+else
+	echo "Cannot locate pack directory"
+	exit 1
+fi
+	
 # list all objects including their size, sort by size, take top 10
-objects=`git verify-pack -v .git/objects/pack/pack-*.idx | grep -v chain | sort -k3nr | head`
+objects=`git verify-pack -v ${PACK_DIR}/pack-*.idx | grep -v chain | sort -k3nr | head`
 
 echo "All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file."
 
